### ISSUE TITLE
Public backlog in Projects kanban

### ISSUE THREAD

**Issue by Kwaskoff** [tonlabs/gosh#86]
https://github.com/tonlabs/gosh/projects?type=beta - there is nothing
When every participant of community can create issue with new features - it can be converted to backlog in kanban.

My first interest of your backlog is "when EVM support?".

**Comment by Futurizt** [comment]
Thanks for the feedback. 
We are not going to use Github features for a simple reason -- that we are goin gto move from Github to Gosh very soon.
What do you mean by "EVM support"? The Gosh network is not EVM compatible. It is asynchronous, has different memory model etc. You can not run Sol contracts written for Gosh in EVM networks.
